name: edge-nns
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - numba
    - numpy
    - pandas
    - matplotlib
    - pillow
    - jupyter
    - tensorflow[and-cuda]==2.15.*
    - tf-keras
    - qkeras==0.9.0
    - tensorflow-model-optimization
    - pot
    - PyYAML
    - scikit-learn
    - tqdm
    - mplhep
    - opencv-python
