data:
  input_shape:
  - 16
  name: jsc
  num_classes: 5
model:
  dense_widths:
  - 64
  - 128
quantization:
  activation_int_bits: 2
  activation_quantizer: quantized_relu
  activation_total_bits: 4
  alpha: 1
  logit_int_bits: 2
  logit_quantizer: quantized_bits
  logit_total_bits: 4
