data:
  input_shape: [16]
  name: jsc
  num_classes: 5

model:
  dense_widths: [32]

quantization:
  activation_int_bits: 4
  activation_quantizer: quantized_relu
  activation_total_bits: 8
  alpha: 1
  logit_int_bits: 2
  logit_quantizer: quantized_bits
  logit_total_bits: 6

fit:
  batch_size: 256
  epochs: 10
  compile:
    optimizer: adam
    learning_rate: 0.001
    loss: sparse_categorical_crossentropy
    metrics: [sparse_categorical_accuracy]
